index:
    path:     /
    defaults: { _controller: EmaGroBlogBundle:Blog:index }

create:
    path:     /create
    defaults: { _controller: EmaGroBlogBundle:Blog:create }

new:
    path:     /new/
    defaults: { _controller: EmaGroBlogBundle:Blog:new }

edit:
    path:     /edit/{iddupost}
    defaults: { _controller: EmaGroBlogBundle:Blog:edit }

admin:
    path:     /admin
    defaults: { _controller: EmaGroBlogBundle:Blog:admin }

delete:
    path:     /delete/{iddupost}
    defaults: { _controller: EmaGroBlogBundle:Blog:delete }

post:
    path:     /post/{slug}
    defaults: { _controller: EmaGroBlogBundle:Blog:post }
    requirements:
            iddupost:  \d+
