create:
    path:     /create
    defaults: { _controller: EmaGroBlogBundle:Crud:create }

new:
    path:     /new/
    defaults: { _controller: EmaGroBlogBundle:Crud:new }

edit:
    path:     /edit/{iddupost}
    defaults: { _controller: EmaGroBlogBundle:Crud:edit }

admin:
    path:     /admin
    defaults: { _controller: EmaGroBlogBundle:Crud:admin }

delete:
    path:     /delete/{iddupost}
    defaults: { _controller: EmaGroBlogBundle:Crud:delete }

index:
    path:     /
    defaults: { _controller: EmaGroBlogBundle:Blog:index }

post:
    path:     /post/{slug}
    defaults: { _controller: EmaGroBlogBundle:Blog:post }
    requirements:
            iddupost:  \d+
